defaults:
  - _self_
  - group: null

hydra:
  searchpath:
    - pkg://lerna.test_utils.configs.completion_test_additional_package
    - file://lerna/test_utils/configs/completion_test_additional_file
